[fix] Suppress errors from `AnalysisSession`
We are getting errors such as:
```
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

According to https://github.com/dart-lang/build/issues/2946, this is likely due to the single state maintained by the analysis server being mutated by multiple clients at the same time.